In [2]:
import numpy as np
class SoftMax():

    def forward(self, x):
        self.x = x
        sigma = 1e-10
        x -= np.max(x, axis=1, keepdims=True)
        return np.exp(x)/np.sum(np.exp(x), axis=1, keepdims=True)

In [3]:
a = np.array([[1,2,3],
              [3,2,1],
              [4,2,3]])
sm = SoftMax().forward(a)

In [4]:
sm

array([[0.09003057, 0.24472847, 0.66524096],
       [0.66524096, 0.24472847, 0.09003057],
       [0.66524096, 0.09003057, 0.24472847]])

In [15]:
a = np.random.rand(1, 3)
print(a)
b = np.random.rand(1, 3)
print(b)
c = np.concatenate((a, b), axis = 0)
print(c)
d = np.concatenate((c, b), axis = 0)
print(d)

[[0.76128019 0.96784519 0.12316184]]
[[0.44987142 0.57549591 0.11344986]]
[[0.76128019 0.96784519 0.12316184]
 [0.44987142 0.57549591 0.11344986]]
[[0.76128019 0.96784519 0.12316184]
 [0.44987142 0.57549591 0.11344986]
 [0.44987142 0.57549591 0.11344986]]


In [26]:
e = np.sort(d, axis=0)
print(e)
print(e[:, 1])
np.sum(e[:, 1])





[[0.44987142 0.57549591 0.11344986]
 [0.44987142 0.57549591 0.11344986]
 [0.76128019 0.96784519 0.12316184]]
[0.57549591 0.57549591 0.96784519]


2.118837000924771